const data = [
  {
    key: 1,
    id: 'twitter',
    url: 'http://twitter.com/danbashi_1',
    sit: '',
    desc: 'Twitter Link',
    target: '_blank',
  },
  {
    key: 2,
    id: 'slack',
    sit: 'none',
    url: 'http://twitter.com/danbashi_1',
    desc: 'Slack',
    target: '_blank',
  },
  {
    key: 4,
    id: 'btn__zuri',
    sit: '',
    url: 'https://training.zuri.team/',
    desc: 'Zuri Team',
    target: '_blank',
  },
  {
    key: 5,
    id: 'books',
    sit: '',
    url: 'https://books.zuri.team/',
    desc: 'Zuri Books',
    target: '_blank',
  },
  {
    key: 6,
    id: 'book__python',
    sit: '',
    url: 'https://books.zuri.team/python-for-beginners?ref_id=AliuBashir',
    desc: 'Python Books',
    target: '_blank',
  },
  {
    key: 7,
    id: 'pitch',
    sit: '',
    url: ' https://background.zuri.team',
    desc: 'Background Check for Coders',
    target: '_blank',
  },
  {
    key: 8,
    id: 'book__design',
    sit: '',
    url: 'https://books.zuri.team/design-rules',
    desc: 'Design Books',
    target: '_blank',
  },
  {
    key: 9,
    id: 'contact',
    sit: '',
    url: '/contacts',
    desc: 'Contact',
    target: '',
  },
]

export default data
